# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: orih@jfrog.com
author_name: Ori Hollander
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_xssguard
project_short_description: A JupyterLab extension to insert code block html output
    into iframe.
python_name: jupyterlab_xssguard
repository: https://github.com/jfrog/jupyterlab-xssguard
test: true

